pub const LITTLE: bool = cfg!(target_endian="little");
pub const BIG:    bool = cfg!(target_endian="big");

// [ANCHOR START] CONST-TO-STRUCT.PY //

/*
 * the following source code is automatic generated by const-to-struct.py
 * DO NOT EDIT.
*/

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct cfg_target_endian_info {
    pub little: bool,
    pub big: bool,
}
pub const ALL_INFO: cfg_target_endian_info = all_info();
pub const fn all_info() -> cfg_target_endian_info {
    cfg_target_endian_info {
        little: LITTLE,
        big: BIG,
    }
}
#[cfg(feature = "json")]
impl cfg_target_endian_info {
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "little": self.little,
            "big": self.big,
        })
    }
}
// [ANCHOR ENDED] CONST-TO-STRUCT.PY //