pub const PC:       bool = cfg!(target_vendor="pc");
pub const APPLE:    bool = cfg!(target_vendor="apple");
pub const FORTANIX: bool = cfg!(target_vendor="fortanix");
pub const UNKNOWN:  bool = cfg!(target_vendor="unknown");

// [ANCHOR START] CONST-TO-STRUCT.PY //

/*
 * the following source code is automatic generated by const-to-struct.py
 * DO NOT EDIT.
*/

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct cfg_target_vendor_info {
    pub pc: bool,
    pub apple: bool,
    pub fortanix: bool,
    pub unknown: bool,
}
pub const ALL_INFO: cfg_target_vendor_info = all_info();
pub const fn all_info() -> cfg_target_vendor_info {
    cfg_target_vendor_info {
        pc: PC,
        apple: APPLE,
        fortanix: FORTANIX,
        unknown: UNKNOWN,
    }
}
#[cfg(feature = "json")]
impl cfg_target_vendor_info {
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "pc": self.pc,
            "apple": self.apple,
            "fortanix": self.fortanix,
            "unknown": self.unknown,
        })
    }
}
// [ANCHOR ENDED] CONST-TO-STRUCT.PY //