pub const _8:   bool = cfg!(target_has_atomic="8");
pub const _16:  bool = cfg!(target_has_atomic="16");
pub const _32:  bool = cfg!(target_has_atomic="32");
pub const _64:  bool = cfg!(target_has_atomic="64");
pub const _128: bool = cfg!(target_has_atomic="128");
pub const PTR:  bool = cfg!(target_has_atomic="ptr");

// [ANCHOR START] CONST-TO-STRUCT.PY //

/*
 * the following source code is automatic generated by const-to-struct.py
 * DO NOT EDIT.
*/

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct cfg_target_has_atomic_info {
    pub _8: bool,
    pub _16: bool,
    pub _32: bool,
    pub _64: bool,
    pub _128: bool,
    pub ptr: bool,
}
pub const ALL_INFO: cfg_target_has_atomic_info = all_info();
pub const fn all_info() -> cfg_target_has_atomic_info {
    cfg_target_has_atomic_info {
        _8: _8,
        _16: _16,
        _32: _32,
        _64: _64,
        _128: _128,
        ptr: PTR,
    }
}
// [ANCHOR ENDED] CONST-TO-STRUCT.PY //