pub const _64: bool = cfg!(target_pointer_width="64");
pub const _32: bool = cfg!(target_pointer_width="32");
pub const _16: bool = cfg!(target_pointer_width="16");

// [ANCHOR START] CONST-TO-STRUCT.PY //

/*
 * the following source code is automatic generated by const-to-struct.py
 * DO NOT EDIT.
*/

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct cfg_target_pointer_width_info {
    pub _64: bool,
    pub _32: bool,
    pub _16: bool,
}
pub const ALL_INFO: cfg_target_pointer_width_info = all_info();
pub const fn all_info() -> cfg_target_pointer_width_info {
    cfg_target_pointer_width_info {
        _64: _64,
        _32: _32,
        _16: _16,
    }
}
#[cfg(feature = "json")]
impl cfg_target_pointer_width_info {
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "_64": self._64,
            "_32": self._32,
            "_16": self._16,
        })
    }
}
// [ANCHOR ENDED] CONST-TO-STRUCT.PY //